mod register;
mod login;
pub mod chat;
mod navbar;
mod forgot_password;
mod reset_password;
mod home;
mod article;
mod rubrique;
mod editor;

pub use register::Register;
pub use login::Login;
pub use chat::Chat;
pub use navbar::Navbar;
pub use forgot_password::ForgotPassword;
pub use reset_password::ResetPassword;
pub use home::Home;
pub use article::Article;
pub use rubrique::Rubrique;
pub use editor::ArticleEditor;